### PR TITLE
added lil hover effects to navbar and make the website less cramped

### PR DESCRIPTION
**Pull request by ashleyirispuppy143**
this pr adds gray color to hovered links so its more visible to the user the link they are clicking :3

it also adds more spacing to text :3

### CODE REVIEW

**Comment by wait-what** [comment]
I don't like the use of `!important` and also this removes `cursor: pointer` from `nav a:hover`?

**Comment by ashleyirispuppy143** [comment]
wait gonna fix

**Comment by ashleyirispuppy143** [comment]
it removes it because you cant have 2 diffrent uhhh definitions for each css class btw

**Comment by ashleyirispuppy143** [comment]
also added more spacing,,

**Comment by DeclanChidlow** [comment]
Won't merge, site is undergoing redevelopment.

**Pull request closed without merging**
